on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1.4
        with:
          src_dir: E:\Catapult-Tec\cms-catapult-hb-theme
          dest_dir: /cms-catapult-hb-theme
          portal_id: ${{ secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
          
          on:
  push:
    branches:
    - DEV
...
portal_id: ${{ secrets.staging_account_id }}
- name: HubSpot Deploy Action
  uses: HubSpot/hubspot-cms-deploy-action@v1.3
  with:
    src_dir: /cms-catapult-hb-theme
    dest_dir: E:\Catapult-Tec\cms-catapult-hb-theme
    portal_id: ${{ secrets.hubspot_portal_id }}
    personal_access_key: ${{ secrets.hubspot_personal_access_key }}
